Fix build system
bakulf/libnxml pull request #5
Opened 2020-03-18 21:36 UTC by dacav

In this PR I'm addressing some little problems I've found when bootstrapping the library.
This is effectively fixing https://github.com/bakulf/libnxml/issues/2

2020-07-19 15:56 UTC, bakulf requested changes
Thanks for doing this. A couple of changes in .gitignore

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +doc/Makefile.in
Just `Makefile.in`. Remove this and any other occurrencies of Makefile.in in this file.

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +src/Makefile.in
remove this and the following one.

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +Makefile
Same here: Just `Makefile` and remove any other ones.

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +src/.deps/
.deps
.libs

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +src/nxml_download.lo
*.lo
*.o

2020-07-19 15:56 UTC, bakulf commented on .gitignore
> +
No empty line.

2020-07-19 19:51 UTC, dacav commented
All solved.  I'm not sure how your merge policy is, but I recommend a `rebase --autosquash` :)

Cheers

2020-07-19 22:21 UTC, dacav commented
I've added a bunch of further fixes...
I had some problems in adding the unit tests that I'm writing to tap the crashes.

2020-08-03 07:57 UTC, dacav commented
The recently pushed clang-format is breaking this PR horribly, so I'm closing it in favour of a new one.

2020-08-03 07:57 UTC, closed without merging